---
deployment:
  tasks:
    - echo "Starting deployment process..."
    - export DEPLOYPATH=/home/akshayka/public_html/
    - echo "Copying files to $DEPLOYPATH..."
    - /bin/cp -R * $DEPLOYPATH
    - echo "Setting permissions for directories and files..."
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - echo "Deployment completed!"
