---
deployment:
  tasks:
    - echo "Starting deployment process..."

    # Define the deployment path
    - export DEPLOYPATH=/home/akshayka/public_html/
    - echo "Deployment path set to $DEPLOYPATH"

    # Clear the contents of public_html to ensure a clean deployment
    - echo "Clearing old files from $DEPLOYPATH..."
    - /bin/rm -rf $DEPLOYPATH/*

    # Copy all files from the 'out' directory (Next.js export) to the deployment path
    - echo "Copying files from 'out' directory to $DEPLOYPATH..."
    - /bin/cp -R out/* $DEPLOYPATH

    # Set permissions: Directories to 755 and files to 644
    - echo "Setting permissions for directories and files..."
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    
    # Optional: Output final confirmation
    - echo "Deployment completed successfully!"
